applications:
  - name: test
    targetGroups:
      - name: group1
        targets:
          - http://localhost:8000/health
          - http://localhost:8001/health
        healthCheckInterval: 10

notifications:
  notification_settings:
    - channel: EMAIL
      receivers:
        - test@test.com
        - test2@test.com

smtp:
  server:
  user:
  password: